# Uncomment the next line to define a global platform for your project
# platform :ios, '12.3'

target 'Chat' do

  pod 'KeychainSwift', '~> 19.0'  

  pod 'PhoneNumberKit', '3.3'

  pod 'MBProgressHUD', '1.2.0'

  pod 'MessageKit'

end
