# Uncomment the next line to define a global platform for your project
# platform :ios, '12.3'

target 'Chat' do
  use_frameworks!

  pod 'KeychainSwift', '~> 19.0'  

  pod 'PhoneNumberKit', '3.3'

  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

  pod 'MessageKit'

end
